"""End-to-end asset pipeline.

This script transforms the raw downloads under build/staging/ into a clean
set of .obj + .mtl + texture trios under assets/modelos/<name>/.

It handles three flavours of input:
1. Already-.obj models  -> copied, .mtl rewritten to point to the chosen
   diffuse texture, texture copied into the same folder.
2. .fbx and .blend models -> read with assimp_py (handles both formats),
   merged into a single mesh, written as .obj.
3. Models without any diffuse texture (Sci Fi Table, fish, chair if it
   cannot be extracted) -> a fallback texture is applied so every model
   ships with a usable map_Kd.

We also generate a procedural diffuse texture for the fish so that the
"todos os modelos com textura" rule is satisfied even without an
external download.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import assimp_py as a
import numpy as np
from PIL import Image


PROJ_ROOT = Path(__file__).resolve().parent.parent
STAGING = PROJ_ROOT / "build" / "staging"
ASSETS = PROJ_ROOT / "assets" / "modelos"
TEX_INTERIOR = PROJ_ROOT / "assets" / "texturas" / "interior" / "metal_brushed.jpg"


def write_min_mtl(mtl_path: Path, material: str, texture_name: str) -> None:
    with mtl_path.open("w") as f:
        f.write(f"# Generated by build_assets.py\n")
        f.write(f"newmtl {material}\n")
        f.write("Ka 1.0 1.0 1.0\n")
        f.write("Kd 1.0 1.0 1.0\n")
        f.write("Ks 0.0 0.0 0.0\n")
        f.write("d 1.0\n")
        f.write("illum 1\n")
        f.write(f"map_Kd {texture_name}\n")


def write_multi_mtl(mtl_path: Path, materials: dict[str, str]) -> None:
    """Write a .mtl with several `newmtl` blocks, one per material name."""
    with mtl_path.open("w") as f:
        f.write("# Generated by build_assets.py\n")
        for name, tex in materials.items():
            f.write(f"\nnewmtl {name}\n")
            f.write("Ka 1.0 1.0 1.0\n")
            f.write("Kd 1.0 1.0 1.0\n")
            f.write("Ks 0.0 0.0 0.0\n")
            f.write("d 1.0\n")
            f.write("illum 1\n")
            f.write(f"map_Kd {tex}\n")


def parse_mtl_colors(mtl_path: Path) -> dict[str, dict[str, tuple[float, float, float]]]:
    """Parse a Wavefront .mtl, returning per-material Kd/Ks/Ka/Ke colours.

    Map structure: { material_name: {"Kd": (r,g,b), "Ke": (r,g,b), ...} }
    Missing entries fall back to defaults at the call site.

    Material names may contain whitespace (e.g. `Main mat A`,
    `Black  Reflection` with two spaces); we capture the full
    `newmtl ` line and collapse runs of whitespace into single
    spaces to keep names unambiguous downstream.
    """
    out: dict[str, dict[str, tuple[float, float, float]]] = {}
    if not mtl_path.exists():
        return out
    current: str | None = None
    for raw in mtl_path.read_text(errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        head, *rest = line.split()
        if head == "newmtl" and rest:
            # Use the full remainder of the original line (after the
            # 'newmtl ' prefix) so a name like 'Main mat A' stays intact.
            stripped = raw.lstrip()
            after_kw = stripped.split(None, 1)[1] if " " in stripped else stripped
            current = " ".join(after_kw.split())
            out[current] = {}
        elif current and head in {"Kd", "Ks", "Ka", "Ke"} and len(rest) >= 3:
            out[current][head] = (float(rest[0]), float(rest[1]), float(rest[2]))
    return out


def parse_mtl_full(mtl_path: Path) -> dict[str, dict]:
    """Parse a .mtl into per-material dicts with `Kd`, `Ke`, `map_Kd`.

    Same whitespace rules as `parse_mtl_colors`.  `map_Kd` is the
    file name *as written in the .mtl* (no path resolution).
    """
    out: dict[str, dict] = {}
    if not mtl_path.exists():
        return out
    current: str | None = None
    for raw in mtl_path.read_text(errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        head, *rest = line.split()
        head_l = head.lower()
        if head_l == "newmtl" and rest:
            stripped = raw.lstrip()
            after_kw = stripped.split(None, 1)[1] if " " in stripped else stripped
            current = " ".join(after_kw.split())
            out[current] = {}
        elif current is None:
            continue
        elif head in {"Kd", "Ks", "Ka", "Ke"} and len(rest) >= 3:
            out[current][head] = (float(rest[0]), float(rest[1]), float(rest[2]))
        elif head_l == "map_kd" and rest:
            # Diffuse texture file name; may itself contain spaces.
            stripped = raw.lstrip()
            after_kw = stripped.split(None, 1)[1] if " " in stripped else stripped
            out[current]["map_Kd"] = after_kw.strip()
    return out


def copy_obj_mixed_materials(
    src_obj: Path,
    src_mtl: Path,
    out_dir: Path,
    obj_name: str,
    texture_search_dirs: list[Path] | None = None,
    black_floor: float = 0.06,
    emissive_blend: float = 0.85,
) -> None:
    """A union of `copy_obj_with_kd_textures` and `copy_obj_multi_material`.

    For each material in the source .mtl:
      * If it declares `map_Kd <name>` AND the file is found in any of
        `texture_search_dirs`, the real image is copied next to the
        new .obj and used as the diffuse map.
      * Otherwise we fall back to a synthetic solid-colour .jpg
        derived from the material's `Kd` (with `Ke` mixed in for
        emissives, à la `copy_obj_with_kd_textures`).

    Material names with spaces are collapsed to single-space form on
    output.  The .obj is rewritten so every `usemtl ...` matches the
    cleaned-up name.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{obj_name}.obj"
    out_mtl = out_dir / f"{obj_name}.mtl"
    materials = parse_mtl_full(src_mtl)
    if not materials:
        raise RuntimeError(f"No materials parsed from {src_mtl}")

    search_dirs = list(texture_search_dirs or [src_mtl.parent])

    def find_texture(name: str) -> Path | None:
        for d in search_dirs:
            p = d / name
            if p.exists():
                return p
        return None

    material_to_texture: dict[str, str] = {}
    for mat_name, props in materials.items():
        safe = "_".join(mat_name.split())  # 'Main mat A' -> 'Main_mat_A'
        tex_target = f"{obj_name}_{safe}"
        map_kd = props.get("map_Kd")
        chosen: Path | None = None
        if map_kd:
            chosen = find_texture(map_kd)

        if chosen is not None:
            ext = chosen.suffix.lower()
            tex_name = f"{tex_target}{ext}"
            shutil.copy(chosen, out_dir / tex_name)
            print(f"  [obj-mix] {obj_name}/{mat_name}: map_Kd={map_kd!r} -> {tex_name}")
        else:
            kd = props.get("Kd", (0.7, 0.7, 0.7))
            ke = props.get("Ke", (0.0, 0.0, 0.0))
            if max(ke) > 0.05:
                mixed = tuple(
                    min(1.0, kd[i] * (1 - emissive_blend) + ke[i] * emissive_blend)
                    for i in range(3)
                )
            else:
                mixed = kd
            rgb = tuple(max(c, black_floor) for c in mixed)
            tex_name = f"{tex_target}.jpg"
            make_solid_color_texture(out_dir / tex_name, rgb)
            print(
                f"  [obj-mix] {obj_name}/{mat_name}: Kd={kd} Ke={ke} -> "
                f"rgb={tuple(round(c,3) for c in rgb)} -> {tex_name}"
            )

        material_to_texture[mat_name] = tex_name

    write_multi_mtl(out_mtl, material_to_texture)

    # Rewrite the .obj: drop pre-existing mtllib lines, point at our
    # new .mtl, and normalise every `usemtl ...` into the cleaned-up
    # space-collapsed material name.
    with src_obj.open("r", errors="ignore") as fin, out_obj.open("w") as fout:
        fout.write(f"# Cleaned copy of {src_obj.name} (mixed materials)\n")
        fout.write(f"mtllib {obj_name}.mtl\n")
        for line in fin:
            stripped = line.lstrip()
            low = stripped.lower()
            if low.startswith("mtllib"):
                continue
            if low.startswith("usemtl "):
                raw_name = stripped.split(None, 1)[1].rstrip()
                cleaned = " ".join(raw_name.split())
                fout.write(f"usemtl {cleaned}\n")
                continue
            fout.write(line)
    print(
        f"  [obj-mix] {obj_name}: copied, {len(materials)} materials "
        f"({sum(1 for p in materials.values() if p.get('map_Kd'))} with real textures) "
        f"-> {out_obj.name}"
    )


def copy_obj_with_kd_textures(
    src_obj: Path,
    src_mtl: Path,
    out_dir: Path,
    obj_name: str,
    black_floor: float = 0.06,
    emissive_blend: float = 0.85,
    skip_materials: set[str] | None = None,
) -> None:
    """Convert an .obj+.mtl that ships with solid `Kd` (no `map_Kd`) into
    a folder of (.obj, .mtl, one tiny solid-colour .jpg per material).

    Black floors:
        Many DCC tools export `Kd = 0,0,0` for materials that rely on
        node-based shading.  A pitch-black submesh is unusable for our
        unlit pipeline, so each channel is clamped to >= `black_floor`.

    Emissives:
        When a material has a non-trivial `Ke` (typical for "screen"
        on sci-fi chairs), we visually fake an emissive look by mixing
        the emissive colour into the diffuse using `emissive_blend`,
        so the tile/screen shows up as the intended cyan/blue glow.

    Skipping materials:
        ``skip_materials`` lists material names that should not appear
        in the output: their texture is not synthesised, the material
        block is dropped from the .mtl, and any ``f ...`` face emitted
        between a ``usemtl <skipped>`` and the next ``usemtl`` (or the
        end of the file) is omitted.  Useful to strip Blender template
        backgrounds (e.g. a 30 m × 30 m skybox plane) that ship in
        downloaded .obj scenes.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{obj_name}.obj"
    out_mtl = out_dir / f"{obj_name}.mtl"
    materials = parse_mtl_colors(src_mtl)

    if not materials:
        raise RuntimeError(f"No materials parsed from {src_mtl}")

    skip = set(skip_materials or ())

    material_to_texture: dict[str, str] = {}
    for mat_name, props in materials.items():
        if mat_name in skip:
            print(f"  [obj-kd] {obj_name}/{mat_name}: skipped (in skip_materials)")
            continue
        kd = props.get("Kd", (0.7, 0.7, 0.7))
        ke = props.get("Ke", (0.0, 0.0, 0.0))
        if max(ke) > 0.05:
            mixed = tuple(min(1.0, kd[i] * (1 - emissive_blend) + ke[i] * emissive_blend) for i in range(3))
        else:
            mixed = kd
        rgb = tuple(max(c, black_floor) for c in mixed)
        safe = "".join(ch if ch.isalnum() else "_" for ch in mat_name)
        tex_name = f"{obj_name}_{safe}.jpg"
        make_solid_color_texture(out_dir / tex_name, rgb)
        material_to_texture[mat_name] = tex_name
        print(
            f"  [obj-kd] {obj_name}/{mat_name}: Kd={kd} Ke={ke} -> rgb={tuple(round(c,3) for c in rgb)} -> {tex_name}"
        )

    write_multi_mtl(out_mtl, material_to_texture)

    # Copy the .obj line-by-line, replacing the mtllib reference with our
    # generated .mtl, dropping pre-existing `mtllib` directives, and
    # filtering out any face emitted under a skipped material.
    skipping_faces = False
    dropped_faces = 0
    with src_obj.open("r", errors="ignore") as fin, out_obj.open("w") as fout:
        fout.write(f"# Cleaned copy of {src_obj.name}\n")
        fout.write(f"mtllib {obj_name}.mtl\n")
        for line in fin:
            stripped = line.lstrip()
            if stripped.startswith("mtllib"):
                continue
            if stripped.startswith("usemtl "):
                name = stripped.split(None, 1)[1].strip()
                skipping_faces = name in skip
                if skipping_faces:
                    continue  # drop the usemtl line for skipped materials
            if skipping_faces and stripped.startswith("f "):
                dropped_faces += 1
                continue
            fout.write(line)
    print(
        f"  [obj-kd] {obj_name}: copied, {len(material_to_texture)} solid-colour "
        f"materials (skipped {len(skip)} matched) -> {out_obj.name}"
        + (f" [-{dropped_faces} faces]" if dropped_faces else "")
    )


def copy_obj_with_texture(
    src_obj: Path,
    out_dir: Path,
    obj_name: str,
    texture_src: Path,
    texture_out_name: str,
) -> None:
    """Copy an existing .obj into the assets folder, force a fresh .mtl
    referencing only the chosen diffuse texture, and copy the texture in.

    The original .obj is rewritten so its `mtllib`/`usemtl` lines point
    at our generated material, and any pre-existing `mtllib`/`usemtl`
    lines are dropped to avoid dangling references.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{obj_name}.obj"
    out_mtl = out_dir / f"{obj_name}.mtl"
    out_tex = out_dir / texture_out_name

    if out_tex.resolve() != texture_src.resolve():
        shutil.copy(texture_src, out_tex)
    write_min_mtl(out_mtl, obj_name, texture_out_name)

    with src_obj.open("r", errors="ignore") as fin, out_obj.open("w") as fout:
        fout.write(f"# Cleaned copy of {src_obj.name}\n")
        fout.write(f"mtllib {obj_name}.mtl\n")
        fout.write(f"usemtl {obj_name}\n")
        for line in fin:
            stripped = line.lstrip()
            if stripped.startswith(("mtllib", "usemtl")):
                continue
            fout.write(line)
    print(f"  [obj] {obj_name}: copied, mtl rewritten -> {out_obj.name}")


def copy_obj_multi_material(
    src_obj: Path,
    out_dir: Path,
    obj_name: str,
    materials: dict[str, tuple[Path, str]],
) -> None:
    """Copy an .obj that has several `usemtl` switches, preserving each.

    `materials` maps the original material name (as it appears in the
    source .obj's `usemtl ...` lines) to a (source_texture_path,
    target_filename) tuple. Each material gets its own newmtl block in
    the generated .mtl, and the textures are copied next to the .obj.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{obj_name}.obj"
    out_mtl = out_dir / f"{obj_name}.mtl"

    # Copy texture files into the model folder.
    for _, (src_path, target_name) in materials.items():
        dst = out_dir / target_name
        if dst.resolve() != src_path.resolve():
            shutil.copy(src_path, dst)

    write_multi_mtl(out_mtl, {name: tex for name, (_, tex) in materials.items()})

    with src_obj.open("r", errors="ignore") as fin, out_obj.open("w") as fout:
        fout.write(f"# Cleaned copy of {src_obj.name} (multi-material)\n")
        fout.write(f"mtllib {obj_name}.mtl\n")
        for line in fin:
            stripped = line.lstrip()
            # Drop the original mtllib (we use ours), but keep usemtl
            # switches verbatim so each face stays bound to its material.
            if stripped.startswith("mtllib"):
                continue
            fout.write(line)
    print(
        f"  [obj] {obj_name}: multi-mat copy, mtl has "
        f"{len(materials)} materials -> {out_obj.name}"
    )


def assimp_to_obj(
    src_path: Path,
    out_dir: Path,
    obj_name: str,
    texture_src: Path | None,
    texture_out_name: str | None,
    flip_v: bool = True,
    pre_transform: bool = True,
    fallback_planar_uv: bool = True,
    skip_mesh_names: set[str] | None = None,
    min_mesh_verts: int = 0,
    per_material_color_textures: bool = False,
) -> None:
    """Read .fbx/.blend with assimp_py, merge meshes, write .obj.

    UVs are flipped on V to convert from D3D-style (V=0 at top) to
    OpenGL-style (V=0 at bottom), matching `flip_y=True` in the texture
    loader.

    If a sub-mesh has no UVs, we synthesise them by planar projection on
    the XZ plane based on the model bounding box, so the diffuse texture
    is still mappable.

    When `per_material_color_textures=True`, every distinct
    Assimp material with a `COLOR_DIFFUSE` value is turned into a tiny
    256x256 solid-colour texture (with subtle noise), the .mtl gets one
    `newmtl` block per material, and the .obj emits a `usemtl` switch
    before each material's faces.  This is how we expose per-part colours
    for models that ship without baked diffuse maps.
    """
    flags = (
        a.Process_Triangulate
        | a.Process_GenUVCoords
        | a.Process_JoinIdenticalVertices
    )
    if pre_transform:
        flags |= a.Process_PreTransformVertices
    scene = a.import_file(str(src_path), flags)

    out_dir.mkdir(parents=True, exist_ok=True)
    obj_path = out_dir / f"{obj_name}.obj"
    mtl_path = out_dir / f"{obj_name}.mtl"

    all_v: list[float] = []
    all_vt: list[float] = []
    # When `per_material_color_textures` is False we keep the original
    # flat list of triangles. When True we group them per material name
    # so we can emit `usemtl` switches in the .obj.
    flat_faces: list[tuple[int, int, int, int, int, int]] = []
    faces_by_mat: dict[str, list[tuple[int, int, int, int, int, int]]] = {}
    v_off = 0
    vt_off = 0
    has_uv = False

    skip_names = skip_mesh_names or set()
    for mesh in scene.meshes:
        if mesh.name in skip_names:
            print(f"  [conv] {obj_name}: skipping mesh '{mesh.name}'")
            continue
        verts = list(mesh.vertices)
        n = len(verts) // 3
        if n < min_mesh_verts:
            print(f"  [conv] {obj_name}: skipping tiny mesh ({n} verts < {min_mesh_verts})")
            continue
        all_v.extend(verts)

        uv_local: list[float] | None = None
        if mesh.texcoords and mesh.texcoords[0] is not None:
            uvs = list(mesh.texcoords[0])
            if len(uvs) >= 2 * n:
                if flip_v:
                    uv_local = []
                    for i in range(n):
                        uv_local.append(uvs[2 * i])
                        uv_local.append(1.0 - uvs[2 * i + 1])
                else:
                    uv_local = uvs[: 2 * n]
                all_vt.extend(uv_local)
                has_uv = True

        if uv_local is None and fallback_planar_uv and n > 0:
            xs = verts[0::3]
            zs = verts[2::3]
            xmin, xmax = min(xs), max(xs)
            zmin, zmax = min(zs), max(zs)
            xr = max(xmax - xmin, 1e-6)
            zr = max(zmax - zmin, 1e-6)
            uv_local = []
            for i in range(n):
                u = (verts[3 * i] - xmin) / xr
                v = (verts[3 * i + 2] - zmin) / zr
                uv_local.append(u)
                uv_local.append(v)
            all_vt.extend(uv_local)
            has_uv = True

        # Resolve the material name for this mesh (used in multi-material mode).
        mat_name_for_mesh = "default"
        if per_material_color_textures and 0 <= mesh.material_index < len(scene.materials):
            raw_name = scene.materials[mesh.material_index].get("NAME", "")
            mat_name_for_mesh = (raw_name.strip() or f"mat{mesh.material_index}")

        inds = list(mesh.indices)
        for t in range(0, len(inds), 3):
            i0, i1, i2 = inds[t], inds[t + 1], inds[t + 2]
            v0, v1, v2 = i0 + v_off + 1, i1 + v_off + 1, i2 + v_off + 1
            if uv_local is not None:
                t0, t1, t2 = i0 + vt_off + 1, i1 + vt_off + 1, i2 + vt_off + 1
            else:
                t0 = t1 = t2 = 0
            face = (v0, t0, v1, t1, v2, t2)
            flat_faces.append(face)
            if per_material_color_textures:
                faces_by_mat.setdefault(mat_name_for_mesh, []).append(face)

        v_off += n
        if uv_local is not None:
            vt_off += len(uv_local) // 2

    n_v = len(all_v) // 3
    n_vt = len(all_vt) // 2
    print(
        f"  [conv] {obj_name}: meshes={len(scene.meshes)} v={n_v} "
        f"vt={n_vt} faces={len(flat_faces)} uv={has_uv}"
    )

    have_tex = bool(texture_src and texture_out_name)

    # ----- Write material library and per-material textures -----
    if per_material_color_textures and faces_by_mat:
        material_to_texture: dict[str, str] = {}
        for mat_name in faces_by_mat:
            # Find the corresponding material in scene.materials.
            rgb = (0.7, 0.7, 0.7)
            for m in scene.materials:
                if (m.get("NAME") or "").strip() == mat_name:
                    cd = m.get("COLOR_DIFFUSE") or [0.7, 0.7, 0.7]
                    rgb = (float(cd[0]), float(cd[1]), float(cd[2]))
                    break
            tex_name = f"{obj_name}_{mat_name}.jpg"
            make_solid_color_texture(out_dir / tex_name, rgb)
            material_to_texture[mat_name] = tex_name
            print(f"  [conv] {obj_name}/{mat_name}: rgb={rgb} -> {tex_name}")
        write_multi_mtl(mtl_path, material_to_texture)
    elif have_tex:
        tex_dst = out_dir / texture_out_name
        if tex_dst.resolve() != Path(texture_src).resolve():
            shutil.copy(texture_src, tex_dst)
        write_min_mtl(mtl_path, obj_name, texture_out_name)

    # ----- Write the .obj -----
    with obj_path.open("w") as f:
        f.write(f"# Converted from {src_path.name}\n")
        if per_material_color_textures and faces_by_mat:
            f.write(f"mtllib {obj_name}.mtl\n")
        elif have_tex:
            f.write(f"mtllib {obj_name}.mtl\n")
        f.write(f"o {obj_name}\n")
        for i in range(n_v):
            f.write(
                f"v {all_v[3 * i]:.6f} {all_v[3 * i + 1]:.6f} {all_v[3 * i + 2]:.6f}\n"
            )
        for i in range(n_vt):
            f.write(f"vt {all_vt[2 * i]:.6f} {all_vt[2 * i + 1]:.6f}\n")

        def emit_faces(fs: list[tuple[int, int, int, int, int, int]]) -> None:
            for v0, t0, v1, t1, v2, t2 in fs:
                if has_uv and t0 != 0:
                    f.write(f"f {v0}/{t0} {v1}/{t1} {v2}/{t2}\n")
                else:
                    f.write(f"f {v0} {v1} {v2}\n")

        if per_material_color_textures and faces_by_mat:
            for mat_name, fs in faces_by_mat.items():
                f.write(f"usemtl {mat_name}\n")
                emit_faces(fs)
        else:
            if have_tex:
                f.write(f"usemtl {obj_name}\n")
            emit_faces(flat_faces)

    print(
        f"  [conv] -> {obj_path.name}"
        + (" (+ multi-mat mtl + per-mat textures)" if per_material_color_textures and faces_by_mat
           else (" (+ mtl + texture)" if have_tex else ""))
    )


def extract_blend_diffuse(
    blend_path: Path,
    out_dir: Path,
    pick_index: int | None = None,
) -> Path | None:
    """Scan a .blend for PNG/JPEG packed images and return the most likely
    diffuse/base-colour map.

    Blender stores packed images as raw bytes inside `PackedFile` blocks,
    so we don't need bpy: scanning the binary for PNG/JPEG signatures
    reliably extracts them.

    Heuristic for picking the diffuse:
      1. Drop tiny images (< 512x512) — those are thumbnails or icons.
      2. Drop greyscale (mode='L') and near-greyscale (per-channel std
         very close to mean delta) — those are AO/roughness/metallic.
      3. Drop images where the average is dominated by blue (z>x,y by a
         comfortable margin) — those are tangent-space normal maps.
      4. Of what remains, pick the highest-resolution colourful image.

    `pick_index` allows callers to bypass the heuristic and grab the
    extracted file by 0-based index; useful when the heuristic fails.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    buf = blend_path.read_bytes()

    PNG_SIG = b"\x89PNG\r\n\x1a\n"
    PNG_END = b"IEND"
    JPEG_SIG = b"\xff\xd8\xff"
    JPEG_END = b"\xff\xd9"

    extracted: list[Path] = []
    pos = 0
    while True:
        i = buf.find(PNG_SIG, pos)
        if i < 0:
            break
        end = buf.find(PNG_END, i + 8)
        if end < 0:
            break
        end_chunk = end + 4 + 4
        out_path = out_dir / f"packed_{len(extracted):02d}.png"
        out_path.write_bytes(buf[i:end_chunk])
        extracted.append(out_path)
        pos = end_chunk

    pos = 0
    while True:
        i = buf.find(JPEG_SIG, pos)
        if i < 0:
            break
        end = buf.find(JPEG_END, i + 3)
        if end < 0:
            break
        end_total = end + 2
        if end_total - i < 1024:
            pos = end_total
            continue
        out_path = out_dir / f"packed_{len(extracted):02d}.jpg"
        out_path.write_bytes(buf[i:end_total])
        extracted.append(out_path)
        pos = end_total

    print(f"  [blend] {blend_path.name}: extracted {len(extracted)} packed image(s)")
    if not extracted:
        return None

    if pick_index is not None and 0 <= pick_index < len(extracted):
        chosen = extracted[pick_index]
        print(f"  [blend] -> diffuse picked by index {pick_index}: {chosen.name}")
        return chosen

    best: tuple[int, Path] | None = None  # (resolution, path)
    for p in extracted:
        try:
            with Image.open(p) as im:
                im.load()
                w, h = im.size
                if min(w, h) < 512:
                    continue
                if im.mode == "L":
                    continue
                arr = np.asarray(im.convert("RGB"))
                mean = arr.mean(axis=(0, 1))
                std = arr.std(axis=(0, 1))
                # Drop near-greyscale AO/roughness atlases.
                colour_range = max(mean) - min(mean)
                if colour_range < 6.0 and max(std) < 30.0:
                    continue
                # Drop tangent-space normal maps (blue-dominant).
                if mean[2] > mean[0] + 30 and mean[2] > mean[1] + 30:
                    continue
                resolution = w * h
                if best is None or resolution > best[0]:
                    best = (resolution, p)
        except Exception:
            continue

    if best is None:
        print("  [blend] heuristic could not pick a diffuse; falling back to first")
        return extracted[0]
    print(f"  [blend] -> diffuse picked by heuristic: {best[1].name}")
    return best[1]


def make_solid_color_texture(
    out_path: Path,
    rgb: tuple[float, float, float],
    size: int = 256,
    noise_amp: float = 8.0,
) -> None:
    """Generate a tile-able 'solid colour with subtle noise' texture.

    `rgb` components are floats in 0..1 (Assimp's COLOR_DIFFUSE format).
    A bit of noise is added so flat-shaded faces don't look completely
    plastic, and so the JPEG compresses meaningfully.
    """
    seed = abs(hash(out_path.name)) & 0xFFFF
    rng = np.random.default_rng(seed)
    base = np.array([rgb[0] * 255.0, rgb[1] * 255.0, rgb[2] * 255.0], dtype=np.float32)
    noise = rng.normal(0.0, noise_amp, size=(size, size, 3)).astype(np.float32)
    arr = np.clip(base + noise, 0.0, 255.0).astype(np.uint8)
    Image.fromarray(arr).save(out_path, quality=92)


def make_brushed_metal_texture(out_path: Path, size: int = 1024) -> None:
    """Synthesise a tile-able brushed-steel albedo (mid-grey + horizontal
    streaks + light blue tint).  No external download required."""
    rng = np.random.default_rng(7)
    base = np.full((size, size, 3), (170, 175, 185), dtype=np.float32)
    noise = rng.normal(0.0, 18.0, size=(size, size)).astype(np.float32)
    streaks = np.cumsum(rng.normal(0.0, 1.2, size=(size, size)).astype(np.float32), axis=1)
    streaks -= streaks.mean()
    streaks *= 1.6 / max(streaks.std(), 1e-6)
    streaks = np.clip(streaks * 9.0, -22.0, 22.0)
    base[..., 0] += noise + streaks
    base[..., 1] += noise + streaks * 0.95
    base[..., 2] += noise + streaks * 0.85
    plate_band = (np.arange(size) % (size // 8) < 2).astype(np.float32)[:, None] * -25.0
    base += plate_band[..., None]
    arr = np.clip(base, 25.0, 240.0).astype(np.uint8)
    Image.fromarray(arr).save(out_path, quality=92)
    print(f"  [tex] generated brushed metal texture -> {out_path.name}")


def main() -> int:
    print("[build_assets] starting")

    # ---------- (0) shared brushed-metal texture for interior props ----------
    TEX_INTERIOR.parent.mkdir(parents=True, exist_ok=True)
    if not TEX_INTERIOR.exists():
        make_brushed_metal_texture(TEX_INTERIOR)

    # ---------- (1) submarine: clean .obj + real Base_Color.png ----------
    submarine_obj_src = STAGING / "submarine_v2" / "submarine.obj"
    submarine_tex_src = STAGING / "submarine_v2" / "Base_Color.png"
    if submarine_obj_src.exists() and submarine_tex_src.exists():
        copy_obj_with_texture(
            submarine_obj_src,
            ASSETS / "submarino",
            "submarino",
            submarine_tex_src,
            "submarino_basecolor.png",
        )
    else:
        print(
            f"[warn] submarine assets missing under {STAGING / 'submarine_v2'}",
            file=sys.stderr,
        )

    # Joystick 2 (.fbx with multi-material, no embedded image textures).
    # Source comes from objetos/joysticker_2/extracted/3d-model.fbx (already
    # unzipped from the user's download).  We feed it through assimp_to_obj
    # in `per_material_color_textures` mode: each Assimp material with a
    # COLOR_DIFFUSE entry becomes a tiny solid-colour .jpg, the .mtl gets
    # one block per material, and the .obj emits the matching `usemtl`
    # switches — so the joystick keeps its 13 distinct part colours.
    joystick_2_fbx = (
        PROJ_ROOT.parent / "objetos" / "joysticker_2"
        / "extracted" / "3d-model.fbx"
    )
    if joystick_2_fbx.exists():
        assimp_to_obj(
            joystick_2_fbx,
            ASSETS / "joystick_2",
            "joystick_2",
            None,
            None,
            per_material_color_textures=True,
        )
    else:
        print(f"[warn] joystick_2 FBX missing at {joystick_2_fbx}", file=sys.stderr)

    # Sci-fi chair (.obj + .mtl).  This second model ships with a clean
    # multi-material .mtl that uses solid `Kd` colours (no `map_Kd`).
    # We synthesise one tiny solid-colour .jpg per material from the
    # author's Kd (and from Ke for the emissive 'screen'), then write
    # a .mtl that references those textures so our unlit pipeline can
    # render each part with its intended colour.
    chair_obj_src = (
        PROJ_ROOT.parent
        / "objetos"
        / "cadeira"
        / "uploads_files_2664895_chair+-+model+sci-fi+2.obj"
    )
    chair_mtl_src = (
        PROJ_ROOT.parent
        / "objetos"
        / "cadeira"
        / "uploads_files_2664895_chair+-+model+sci-fi+2.mtl"
    )
    if chair_obj_src.exists() and chair_mtl_src.exists():
        copy_obj_with_kd_textures(
            chair_obj_src,
            chair_mtl_src,
            ASSETS / "cadeira",
            "cadeira",
        )
    else:
        print(f"[warn] chair assets missing at {chair_obj_src}", file=sys.stderr)

    # ---------- (2) models already in .obj ----------
    # Coral (AlienTubes) -> Red_Diffuse
    coral_obj = STAGING / "coral" / "AlienTubes_Obj" / "AlienTubes.obj"
    coral_tex = STAGING / "coral" / "AlienTubes_Red_Diffuse.png"
    if coral_obj.exists() and coral_tex.exists():
        copy_obj_with_texture(
            coral_obj,
            ASSETS / "coral",
            "coral",
            coral_tex,
            "coral_diffuse.png",
        )

    # Stone -> stone_01_albedo.jpg
    stone_obj = STAGING / "pedra" / "Stone_01_BaseTri.OBJ"
    stone_tex = STAGING / "pedra" / "stone_01_albedo.jpg"
    if stone_obj.exists() and stone_tex.exists():
        copy_obj_with_texture(
            stone_obj,
            ASSETS / "pedra",
            "pedra",
            stone_tex,
            "pedra_albedo.jpg",
        )

    # Sci-fi table (.obj + .mtl + 9 materials).  The .obj zip ships a
    # clean .mtl that uses Kd colours for 7 of the 9 materials and
    # references two HUD images (`futuristic-hud-15-.jpg`, `Hud 2.png`)
    # for the remaining two.  Those images are NOT in the .obj zip,
    # but they ARE packed inside the matching .fbx.  So we extract
    # them once, rename them to match the .mtl file names, and feed
    # everything through `copy_obj_mixed_materials`.
    table_obj = STAGING / "table" / "obj" / "Sci Fi Table.obj"
    table_mtl = STAGING / "table" / "obj" / "Sci_Fi_Table.mtl"
    table_fbx = PROJ_ROOT.parent / "objetos" / "table" / "uploads_files_6054109_fbx.zip"
    if table_obj.exists() and table_mtl.exists() and table_fbx.exists():
        table_tex_dir = STAGING / "table" / "extracted_textures"
        table_tex_dir.mkdir(parents=True, exist_ok=True)
        # First extract the .fbx, then sniff its bytes for packed PNGs/JPEGs.
        # `extract_blend_diffuse` does the sniffing in-place — but here we
        # need *both* images named exactly as the .mtl asks, so we use the
        # lower-level `extract_blend_textures.py` payload by inlining its
        # logic (PNG_SIG/JPEG_SIG scan).
        fbx_root = STAGING / "table_fbx"
        fbx_root.mkdir(parents=True, exist_ok=True)
        import subprocess
        subprocess.run(
            ["bsdtar", "-xf", str(table_fbx), "-C", str(fbx_root)],
            check=True,
        )
        fbx_path = next(fbx_root.rglob("*.fbx"))
        buf = fbx_path.read_bytes()
        png_sig = b"\x89PNG\r\n\x1a\n"
        jpg_sig = b"\xff\xd8\xff"
        # PNG -> Hud 2.png  (the medical HUD with the human silhouette)
        i = buf.find(png_sig)
        if i >= 0:
            j = buf.find(b"IEND", i + 8)
            if j > 0:
                end = j + 8
                (table_tex_dir / "Hud 2.png").write_bytes(buf[i:end])
                print(f"  [tex] extracted FBX-packed PNG -> 'Hud 2.png'")
        # JPEG -> futuristic-hud-15-.jpg  (the circular dial HUD)
        i = buf.find(jpg_sig)
        if i >= 0:
            j = buf.find(b"\xff\xd9", i + 3)
            if j > 0:
                end = j + 2
                (table_tex_dir / "futuristic-hud-15-.jpg").write_bytes(buf[i:end])
                print(f"  [tex] extracted FBX-packed JPEG -> 'futuristic-hud-15-.jpg'")
        copy_obj_mixed_materials(
            table_obj,
            table_mtl,
            ASSETS / "mesa",
            "mesa",
            texture_search_dirs=[table_tex_dir, table_mtl.parent],
        )
    else:
        print(f"[warn] sci-fi table assets missing", file=sys.stderr)

    # Monitoring station -> two materials: 'table' and 'hologram_glass'.
    # Source already extracted under objetos/monitoring-station/ so we
    # don't need to unzip anything at build time.
    station_root = PROJ_ROOT.parent / "objetos" / "monitoring-station"
    station_obj = station_root / "source" / "Stol2.obj"
    station_tex_table = station_root / "textures" / "table_Base_color.png"
    station_tex_holo = station_root / "textures" / "hologram_glass_Base_color.png"
    if station_obj.exists() and station_tex_table.exists() and station_tex_holo.exists():
        copy_obj_multi_material(
            station_obj,
            ASSETS / "estacao",
            "estacao",
            {
                "table": (station_tex_table, "estacao_table.png"),
                "hologram_glass": (station_tex_holo, "estacao_hologram.png"),
            },
        )
    else:
        print(f"[warn] monitoring station assets missing under {station_root}", file=sys.stderr)

    # Alga (seaweed): single-material .obj + .mtl with map_Kd ->
    # seaweed_diffuse.png (texture ships in a sibling .zip we already
    # extract under objetos/alga/textures_extracted/).  Behaves just like
    # bau/coral/pedra: 1 model, 1 diffuse map, no per-material magic.
    alga_root = PROJ_ROOT.parent / "objetos" / "alga"
    alga_obj = alga_root / "uploads_files_2301153_seaweedList.obj"
    alga_tex = alga_root / "textures_extracted" / "seaweed_diffuse.png"
    if alga_obj.exists() and alga_tex.exists():
        copy_obj_with_texture(
            alga_obj,
            ASSETS / "alga",
            "alga",
            alga_tex,
            "alga_diffuse.png",
        )
    else:
        print(f"[warn] alga assets missing under {alga_root}", file=sys.stderr)

    # ---------- (3) marine animals (.obj + .mtl with Kd-only) ----------
    # Each one ships a Wavefront .obj and a Blender-exported .mtl whose
    # materials only set Kd (no map_Kd / no texture file). We fold them
    # through `copy_obj_with_kd_textures` to synthesise one tiny solid
    # JPEG per material, so the unlit pipeline can render them directly.

    palhaco_obj = (
        PROJ_ROOT.parent / "objetos" / "peixe_palhaco"
        / "obj_extracted" / "pez3.obj"
    )
    palhaco_mtl = palhaco_obj.with_suffix(".mtl")
    if palhaco_obj.exists() and palhaco_mtl.exists():
        # Material.005 in the Blender source is a 30x30 background plane
        # (the blue "skybox" the artist used while modelling); we drop it
        # so only the actual fish geometry survives.
        copy_obj_with_kd_textures(
            palhaco_obj,
            palhaco_mtl,
            ASSETS / "peixe_palhaco",
            "peixe_palhaco",
            skip_materials={"Material.005"},
        )
    else:
        print(f"[warn] peixe_palhaco assets missing at {palhaco_obj}", file=sys.stderr)

    orca_obj = (
        PROJ_ROOT.parent / "objetos" / "orca"
        / "uploads_files_6947089_Orca_LowPoly.obj"
    )
    orca_mtl = orca_obj.with_suffix(".mtl")
    if orca_obj.exists() and orca_mtl.exists():
        copy_obj_with_kd_textures(
            orca_obj,
            orca_mtl,
            ASSETS / "orca",
            "orca",
        )
    else:
        print(f"[warn] orca assets missing at {orca_obj}", file=sys.stderr)

    beluga_obj = (
        PROJ_ROOT.parent / "objetos" / "beluga"
        / "uploads_files_2833308_beluga.obj"
    )
    beluga_mtl = beluga_obj.with_suffix(".mtl")
    if beluga_obj.exists() and beluga_mtl.exists():
        copy_obj_with_kd_textures(
            beluga_obj,
            beluga_mtl,
            ASSETS / "beluga",
            "beluga",
        )
    else:
        print(f"[warn] beluga assets missing at {beluga_obj}", file=sys.stderr)

    print("[build_assets] done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
