"""Pipeline de assets do projeto, ponta a ponta.

Este script transforma os downloads brutos que ficam em ``build/staging/``
(modelos baixados de free3d, CGTrader, BlendSwap, etc.) em um conjunto
limpo de trios ``.obj`` + ``.mtl`` + textura dentro de
``assets/modelos/<nome>/``, no formato exato que o runtime do projeto
espera carregar.

Ele lida com três sabores de entrada:

1. **Modelos que já vêm em ``.obj``** -> são copiados, o ``.mtl`` é
   reescrito para apontar para a textura difusa escolhida e a textura
   é copiada para a mesma pasta.
2. **Modelos em ``.fbx`` / ``.blend``** -> são lidos com ``assimp_py``
   (que entende os dois formatos), todas as malhas são unidas em um
   único mesh e o resultado é gravado como ``.obj``.
3. **Modelos sem nenhuma textura difusa** (mesa sci-fi, peixe-palhaço,
   cadeira nos casos em que ela não pode ser extraída) -> aplicamos
   uma textura procedural de fallback, garantindo que **todo** modelo
   saia daqui já com um ``map_Kd`` utilizável.

Também geramos uma textura difusa procedural para o peixe, de forma que
a regra "todos os modelos com textura" do edital seja atendida mesmo
sem nenhum download externo extra.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import assimp_py as a
import numpy as np
from PIL import Image


PROJ_ROOT = Path(__file__).resolve().parent.parent
STAGING = PROJ_ROOT / "build" / "staging"
ASSETS = PROJ_ROOT / "assets" / "modelos"
TEX_INTERIOR = PROJ_ROOT / "assets" / "texturas" / "interior" / "metal_brushed.jpg"


def write_min_mtl(mtl_path: Path, material: str, texture_name: str) -> None:
    with mtl_path.open("w") as f:
        f.write(f"# Generated by build_assets.py\n")
        f.write(f"newmtl {material}\n")
        f.write("Ka 1.0 1.0 1.0\n")
        f.write("Kd 1.0 1.0 1.0\n")
        f.write("Ks 0.0 0.0 0.0\n")
        f.write("d 1.0\n")
        f.write("illum 1\n")
        f.write(f"map_Kd {texture_name}\n")


def write_multi_mtl(mtl_path: Path, materials: dict[str, str]) -> None:
    """Escreve um ``.mtl`` com vários blocos ``newmtl``, um por nome de material."""
    with mtl_path.open("w") as f:
        f.write("# Generated by build_assets.py\n")
        for name, tex in materials.items():
            f.write(f"\nnewmtl {name}\n")
            f.write("Ka 1.0 1.0 1.0\n")
            f.write("Kd 1.0 1.0 1.0\n")
            f.write("Ks 0.0 0.0 0.0\n")
            f.write("d 1.0\n")
            f.write("illum 1\n")
            f.write(f"map_Kd {tex}\n")


def parse_mtl_colors(mtl_path: Path) -> dict[str, dict[str, tuple[float, float, float]]]:
    """Faz o parse de um ``.mtl`` Wavefront, devolvendo as cores Kd/Ks/Ka/Ke
    de cada material.

    Estrutura do dicionário retornado:
        ``{ nome_do_material: {"Kd": (r,g,b), "Ke": (r,g,b), ...} }``

    Entradas ausentes caem nos defaults definidos pelo chamador.

    Nomes de material podem conter espaços (por exemplo ``Main mat A``,
    ou ``Black  Reflection`` com dois espaços). Capturamos a linha
    ``newmtl ...`` inteira e colapsamos sequências de espaços em um
    único espaço, para manter os nomes inequívocos no resto do
    pipeline.
    """
    out: dict[str, dict[str, tuple[float, float, float]]] = {}
    if not mtl_path.exists():
        return out
    current: str | None = None
    for raw in mtl_path.read_text(errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        head, *rest = line.split()
        if head == "newmtl" and rest:
            # Usa o resto inteiro da linha original (após o prefixo
            # 'newmtl ') para que um nome como 'Main mat A' chegue
            # íntegro, em vez de ser quebrado em tokens.
            stripped = raw.lstrip()
            after_kw = stripped.split(None, 1)[1] if " " in stripped else stripped
            current = " ".join(after_kw.split())
            out[current] = {}
        elif current and head in {"Kd", "Ks", "Ka", "Ke"} and len(rest) >= 3:
            out[current][head] = (float(rest[0]), float(rest[1]), float(rest[2]))
    return out


def parse_mtl_full(mtl_path: Path) -> dict[str, dict]:
    """Faz o parse de um ``.mtl`` em dicionários por material, contendo
    ``Kd``, ``Ke`` e ``map_Kd``.

    Mesmas regras de espaço em branco do ``parse_mtl_colors``. O campo
    ``map_Kd`` é o nome do arquivo *exatamente como aparece no .mtl*,
    sem nenhuma resolução de path.
    """
    out: dict[str, dict] = {}
    if not mtl_path.exists():
        return out
    current: str | None = None
    for raw in mtl_path.read_text(errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        head, *rest = line.split()
        head_l = head.lower()
        if head_l == "newmtl" and rest:
            stripped = raw.lstrip()
            after_kw = stripped.split(None, 1)[1] if " " in stripped else stripped
            current = " ".join(after_kw.split())
            out[current] = {}
        elif current is None:
            continue
        elif head in {"Kd", "Ks", "Ka", "Ke"} and len(rest) >= 3:
            out[current][head] = (float(rest[0]), float(rest[1]), float(rest[2]))
        elif head_l == "map_kd" and rest:
            # Nome do arquivo da textura difusa; ele próprio pode conter
            # espaços, então capturamos o sufixo da linha inteira.
            stripped = raw.lstrip()
            after_kw = stripped.split(None, 1)[1] if " " in stripped else stripped
            out[current]["map_Kd"] = after_kw.strip()
    return out


def copy_obj_mixed_materials(
    src_obj: Path,
    src_mtl: Path,
    out_dir: Path,
    obj_name: str,
    texture_search_dirs: list[Path] | None = None,
    black_floor: float = 0.06,
    emissive_blend: float = 0.85,
) -> None:
    """União de ``copy_obj_with_kd_textures`` e ``copy_obj_multi_material``.

    Para cada material do ``.mtl`` de origem:

    * Se ele declara ``map_Kd <nome>`` E o arquivo é encontrado em
      algum dos diretórios de ``texture_search_dirs``, a imagem real
      é copiada para o lado do novo ``.obj`` e usada como mapa
      difuso.
    * Caso contrário, caímos no fallback de gerar um ``.jpg`` sintético
      de cor sólida a partir do ``Kd`` do material (com o ``Ke``
      misturado para os emissivos, no mesmo estilo de
      ``copy_obj_with_kd_textures``).

    Nomes de material que contêm espaços são colapsados para a forma
    com um único espaço na saída. O ``.obj`` é reescrito de modo que
    todo ``usemtl ...`` referencie o nome já normalizado.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{obj_name}.obj"
    out_mtl = out_dir / f"{obj_name}.mtl"
    materials = parse_mtl_full(src_mtl)
    if not materials:
        raise RuntimeError(f"No materials parsed from {src_mtl}")

    search_dirs = list(texture_search_dirs or [src_mtl.parent])

    def find_texture(name: str) -> Path | None:
        for d in search_dirs:
            p = d / name
            if p.exists():
                return p
        return None

    material_to_texture: dict[str, str] = {}
    for mat_name, props in materials.items():
        safe = "_".join(mat_name.split())  # 'Main mat A' -> 'Main_mat_A'
        tex_target = f"{obj_name}_{safe}"
        map_kd = props.get("map_Kd")
        chosen: Path | None = None
        if map_kd:
            chosen = find_texture(map_kd)

        if chosen is not None:
            ext = chosen.suffix.lower()
            tex_name = f"{tex_target}{ext}"
            shutil.copy(chosen, out_dir / tex_name)
            print(f"  [obj-mix] {obj_name}/{mat_name}: map_Kd={map_kd!r} -> {tex_name}")
        else:
            kd = props.get("Kd", (0.7, 0.7, 0.7))
            ke = props.get("Ke", (0.0, 0.0, 0.0))
            if max(ke) > 0.05:
                mixed = tuple(
                    min(1.0, kd[i] * (1 - emissive_blend) + ke[i] * emissive_blend)
                    for i in range(3)
                )
            else:
                mixed = kd
            rgb = tuple(max(c, black_floor) for c in mixed)
            tex_name = f"{tex_target}.jpg"
            make_solid_color_texture(out_dir / tex_name, rgb)
            print(
                f"  [obj-mix] {obj_name}/{mat_name}: Kd={kd} Ke={ke} -> "
                f"rgb={tuple(round(c,3) for c in rgb)} -> {tex_name}"
            )

        material_to_texture[mat_name] = tex_name

    write_multi_mtl(out_mtl, material_to_texture)

    # Reescreve o .obj: descarta as linhas mtllib pré-existentes,
    # aponta para o nosso novo .mtl e normaliza todo `usemtl ...`
    # para o nome de material já com espaços colapsados.
    with src_obj.open("r", errors="ignore") as fin, out_obj.open("w") as fout:
        fout.write(f"# Cleaned copy of {src_obj.name} (mixed materials)\n")
        fout.write(f"mtllib {obj_name}.mtl\n")
        for line in fin:
            stripped = line.lstrip()
            low = stripped.lower()
            if low.startswith("mtllib"):
                continue
            if low.startswith("usemtl "):
                raw_name = stripped.split(None, 1)[1].rstrip()
                cleaned = " ".join(raw_name.split())
                fout.write(f"usemtl {cleaned}\n")
                continue
            fout.write(line)
    print(
        f"  [obj-mix] {obj_name}: copied, {len(materials)} materials "
        f"({sum(1 for p in materials.values() if p.get('map_Kd'))} with real textures) "
        f"-> {out_obj.name}"
    )


def copy_obj_with_kd_textures(
    src_obj: Path,
    src_mtl: Path,
    out_dir: Path,
    obj_name: str,
    black_floor: float = 0.06,
    emissive_blend: float = 0.85,
    skip_materials: set[str] | None = None,
) -> None:
    """Converte um par ``.obj`` + ``.mtl`` que vem com ``Kd`` sólido (sem
    ``map_Kd``) em uma pasta com (``.obj``, ``.mtl``, um pequeno ``.jpg``
    de cor sólida por material).

    Piso preto (``black_floor``):
        Várias ferramentas de DCC exportam ``Kd = 0,0,0`` para materiais
        que dependem de shading nodal. Uma sub-malha completamente
        preta é inútil para o nosso pipeline *unlit*, então cada canal
        é elevado para no mínimo ``black_floor``.

    Emissivos (``emissive_blend``):
        Quando um material tem um ``Ke`` não-trivial (típico para a
        material "screen" de cadeiras sci-fi), simulamos visualmente
        o efeito emissivo misturando a cor emissiva no difuso na
        proporção ``emissive_blend``. Assim a tela aparece com o
        glow ciano/azul que o autor pretendia.

    Pulando materiais (``skip_materials``):
        Lista de nomes de materiais que **não** devem aparecer na
        saída: a textura deles não é gerada, o bloco no ``.mtl`` é
        descartado, e qualquer linha ``f ...`` (face) emitida entre
        um ``usemtl <descartado>`` e o próximo ``usemtl`` (ou o fim
        do arquivo) também é descartada. Útil para tirar planos de
        fundo de cenas Blender (por exemplo um plano-skybox 30 m × 30 m)
        que vêm embutidos em downloads de ``.obj``.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{obj_name}.obj"
    out_mtl = out_dir / f"{obj_name}.mtl"
    materials = parse_mtl_colors(src_mtl)

    if not materials:
        raise RuntimeError(f"No materials parsed from {src_mtl}")

    skip = set(skip_materials or ())

    material_to_texture: dict[str, str] = {}
    for mat_name, props in materials.items():
        if mat_name in skip:
            print(f"  [obj-kd] {obj_name}/{mat_name}: skipped (in skip_materials)")
            continue
        kd = props.get("Kd", (0.7, 0.7, 0.7))
        ke = props.get("Ke", (0.0, 0.0, 0.0))
        if max(ke) > 0.05:
            mixed = tuple(min(1.0, kd[i] * (1 - emissive_blend) + ke[i] * emissive_blend) for i in range(3))
        else:
            mixed = kd
        rgb = tuple(max(c, black_floor) for c in mixed)
        safe = "".join(ch if ch.isalnum() else "_" for ch in mat_name)
        tex_name = f"{obj_name}_{safe}.jpg"
        make_solid_color_texture(out_dir / tex_name, rgb)
        material_to_texture[mat_name] = tex_name
        print(
            f"  [obj-kd] {obj_name}/{mat_name}: Kd={kd} Ke={ke} -> rgb={tuple(round(c,3) for c in rgb)} -> {tex_name}"
        )

    write_multi_mtl(out_mtl, material_to_texture)

    # Copia o .obj linha a linha, trocando a referência de mtllib pelo
    # nosso .mtl gerado, descartando diretivas `mtllib` pré-existentes
    # e filtrando qualquer face emitida sob um material que foi
    # marcado para pular.
    skipping_faces = False
    dropped_faces = 0
    with src_obj.open("r", errors="ignore") as fin, out_obj.open("w") as fout:
        fout.write(f"# Cleaned copy of {src_obj.name}\n")
        fout.write(f"mtllib {obj_name}.mtl\n")
        for line in fin:
            stripped = line.lstrip()
            if stripped.startswith("mtllib"):
                continue
            if stripped.startswith("usemtl "):
                name = stripped.split(None, 1)[1].strip()
                skipping_faces = name in skip
                if skipping_faces:
                    continue  # também descarta a linha usemtl do material pulado
            if skipping_faces and stripped.startswith("f "):
                dropped_faces += 1
                continue
            fout.write(line)
    print(
        f"  [obj-kd] {obj_name}: copied, {len(material_to_texture)} solid-colour "
        f"materials (skipped {len(skip)} matched) -> {out_obj.name}"
        + (f" [-{dropped_faces} faces]" if dropped_faces else "")
    )


def copy_obj_with_texture(
    src_obj: Path,
    out_dir: Path,
    obj_name: str,
    texture_src: Path,
    texture_out_name: str,
) -> None:
    """Copia um ``.obj`` já existente para a pasta de assets, força um
    ``.mtl`` novo que referencia somente a textura difusa escolhida e
    copia a própria textura para o lado.

    O ``.obj`` original é reescrito de forma que suas linhas
    ``mtllib`` / ``usemtl`` apontem para o nosso material gerado;
    quaisquer ``mtllib`` / ``usemtl`` pré-existentes são descartados
    para evitar referências penduradas para arquivos que não
    estarão na pasta final.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{obj_name}.obj"
    out_mtl = out_dir / f"{obj_name}.mtl"
    out_tex = out_dir / texture_out_name

    if out_tex.resolve() != texture_src.resolve():
        shutil.copy(texture_src, out_tex)
    write_min_mtl(out_mtl, obj_name, texture_out_name)

    with src_obj.open("r", errors="ignore") as fin, out_obj.open("w") as fout:
        fout.write(f"# Cleaned copy of {src_obj.name}\n")
        fout.write(f"mtllib {obj_name}.mtl\n")
        fout.write(f"usemtl {obj_name}\n")
        for line in fin:
            stripped = line.lstrip()
            if stripped.startswith(("mtllib", "usemtl")):
                continue
            fout.write(line)
    print(f"  [obj] {obj_name}: copied, mtl rewritten -> {out_obj.name}")


def copy_obj_multi_material(
    src_obj: Path,
    out_dir: Path,
    obj_name: str,
    materials: dict[str, tuple[Path, str]],
) -> None:
    """Copia um ``.obj`` que tem várias chaves ``usemtl``, preservando
    cada uma delas.

    O dicionário ``materials`` mapeia o nome original do material
    (exatamente como aparece nas linhas ``usemtl ...`` do ``.obj`` de
    origem) para uma tupla ``(caminho_da_textura_origem,
    nome_de_arquivo_alvo)``. Cada material recebe seu próprio bloco
    ``newmtl`` no ``.mtl`` gerado, e as texturas são copiadas para o
    lado do ``.obj``.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{obj_name}.obj"
    out_mtl = out_dir / f"{obj_name}.mtl"

    # Copia os arquivos de textura para a pasta do modelo.
    for _, (src_path, target_name) in materials.items():
        dst = out_dir / target_name
        if dst.resolve() != src_path.resolve():
            shutil.copy(src_path, dst)

    write_multi_mtl(out_mtl, {name: tex for name, (_, tex) in materials.items()})

    with src_obj.open("r", errors="ignore") as fin, out_obj.open("w") as fout:
        fout.write(f"# Cleaned copy of {src_obj.name} (multi-material)\n")
        fout.write(f"mtllib {obj_name}.mtl\n")
        for line in fin:
            stripped = line.lstrip()
            # Descarta o mtllib original (usamos o nosso), mas mantém
            # cada `usemtl` exatamente como veio, para que cada face
            # continue ligada ao seu material.
            if stripped.startswith("mtllib"):
                continue
            fout.write(line)
    print(
        f"  [obj] {obj_name}: multi-mat copy, mtl has "
        f"{len(materials)} materials -> {out_obj.name}"
    )


def assimp_to_obj(
    src_path: Path,
    out_dir: Path,
    obj_name: str,
    texture_src: Path | None,
    texture_out_name: str | None,
    flip_v: bool = True,
    pre_transform: bool = True,
    fallback_planar_uv: bool = True,
    skip_mesh_names: set[str] | None = None,
    min_mesh_verts: int = 0,
    per_material_color_textures: bool = False,
) -> None:
    """Lê um arquivo ``.fbx`` / ``.blend`` com ``assimp_py``, une as
    malhas e escreve um ``.obj``.

    UVs:
        São invertidas no eixo V, convertendo do convênio D3D
        (V=0 no topo) para o convênio OpenGL (V=0 na base). Isso
        casa com o ``flip_y=True`` que usamos no carregador de
        texturas, mantendo as imagens orientadas corretamente.

    UV de fallback:
        Se uma sub-malha vier sem UVs, sintetizamos coordenadas via
        projeção planar no plano XZ baseada no *bounding box* do
        modelo. Assim a textura difusa ainda fica mapeável, mesmo
        que de forma esticada — é melhor do que renderizar sem
        textura.

    Multi-material por cor (``per_material_color_textures=True``):
        Cada material distinto do Assimp que tenha um valor
        ``COLOR_DIFFUSE`` é convertido em uma pequena textura
        256×256 de cor sólida (com um leve ruído). O ``.mtl`` ganha
        um bloco ``newmtl`` por material e o ``.obj`` emite um
        ``usemtl`` antes das faces de cada material. É assim que
        expomos as cores por parte para modelos que vêm sem mapas
        difusos pré-baked.
    """
    flags = (
        a.Process_Triangulate
        | a.Process_GenUVCoords
        | a.Process_JoinIdenticalVertices
    )
    if pre_transform:
        flags |= a.Process_PreTransformVertices
    scene = a.import_file(str(src_path), flags)

    out_dir.mkdir(parents=True, exist_ok=True)
    obj_path = out_dir / f"{obj_name}.obj"
    mtl_path = out_dir / f"{obj_name}.mtl"

    all_v: list[float] = []
    all_vt: list[float] = []
    # Quando `per_material_color_textures` é False mantemos a lista
    # plana de triângulos. Quando é True, agrupamos por nome de
    # material, para podermos emitir os switches de `usemtl` no .obj.
    flat_faces: list[tuple[int, int, int, int, int, int]] = []
    faces_by_mat: dict[str, list[tuple[int, int, int, int, int, int]]] = {}
    v_off = 0
    vt_off = 0
    has_uv = False

    skip_names = skip_mesh_names or set()
    for mesh in scene.meshes:
        if mesh.name in skip_names:
            print(f"  [conv] {obj_name}: skipping mesh '{mesh.name}'")
            continue
        verts = list(mesh.vertices)
        n = len(verts) // 3
        if n < min_mesh_verts:
            print(f"  [conv] {obj_name}: skipping tiny mesh ({n} verts < {min_mesh_verts})")
            continue
        all_v.extend(verts)

        uv_local: list[float] | None = None
        if mesh.texcoords and mesh.texcoords[0] is not None:
            uvs = list(mesh.texcoords[0])
            if len(uvs) >= 2 * n:
                if flip_v:
                    uv_local = []
                    for i in range(n):
                        uv_local.append(uvs[2 * i])
                        uv_local.append(1.0 - uvs[2 * i + 1])
                else:
                    uv_local = uvs[: 2 * n]
                all_vt.extend(uv_local)
                has_uv = True

        if uv_local is None and fallback_planar_uv and n > 0:
            xs = verts[0::3]
            zs = verts[2::3]
            xmin, xmax = min(xs), max(xs)
            zmin, zmax = min(zs), max(zs)
            xr = max(xmax - xmin, 1e-6)
            zr = max(zmax - zmin, 1e-6)
            uv_local = []
            for i in range(n):
                u = (verts[3 * i] - xmin) / xr
                v = (verts[3 * i + 2] - zmin) / zr
                uv_local.append(u)
                uv_local.append(v)
            all_vt.extend(uv_local)
            has_uv = True

        # Resolve o nome do material desta malha (usado no modo
        # multi-material).
        mat_name_for_mesh = "default"
        if per_material_color_textures and 0 <= mesh.material_index < len(scene.materials):
            raw_name = scene.materials[mesh.material_index].get("NAME", "")
            mat_name_for_mesh = (raw_name.strip() or f"mat{mesh.material_index}")

        inds = list(mesh.indices)
        for t in range(0, len(inds), 3):
            i0, i1, i2 = inds[t], inds[t + 1], inds[t + 2]
            v0, v1, v2 = i0 + v_off + 1, i1 + v_off + 1, i2 + v_off + 1
            if uv_local is not None:
                t0, t1, t2 = i0 + vt_off + 1, i1 + vt_off + 1, i2 + vt_off + 1
            else:
                t0 = t1 = t2 = 0
            face = (v0, t0, v1, t1, v2, t2)
            flat_faces.append(face)
            if per_material_color_textures:
                faces_by_mat.setdefault(mat_name_for_mesh, []).append(face)

        v_off += n
        if uv_local is not None:
            vt_off += len(uv_local) // 2

    n_v = len(all_v) // 3
    n_vt = len(all_vt) // 2
    print(
        f"  [conv] {obj_name}: meshes={len(scene.meshes)} v={n_v} "
        f"vt={n_vt} faces={len(flat_faces)} uv={has_uv}"
    )

    have_tex = bool(texture_src and texture_out_name)

    # ----- Escreve a biblioteca de materiais e as texturas por material -----
    if per_material_color_textures and faces_by_mat:
        material_to_texture: dict[str, str] = {}
        for mat_name in faces_by_mat:
            # Procura o material correspondente em scene.materials.
            rgb = (0.7, 0.7, 0.7)
            for m in scene.materials:
                if (m.get("NAME") or "").strip() == mat_name:
                    cd = m.get("COLOR_DIFFUSE") or [0.7, 0.7, 0.7]
                    rgb = (float(cd[0]), float(cd[1]), float(cd[2]))
                    break
            tex_name = f"{obj_name}_{mat_name}.jpg"
            make_solid_color_texture(out_dir / tex_name, rgb)
            material_to_texture[mat_name] = tex_name
            print(f"  [conv] {obj_name}/{mat_name}: rgb={rgb} -> {tex_name}")
        write_multi_mtl(mtl_path, material_to_texture)
    elif have_tex:
        tex_dst = out_dir / texture_out_name
        if tex_dst.resolve() != Path(texture_src).resolve():
            shutil.copy(texture_src, tex_dst)
        write_min_mtl(mtl_path, obj_name, texture_out_name)

    # ----- Escreve o .obj propriamente dito -----
    with obj_path.open("w") as f:
        f.write(f"# Converted from {src_path.name}\n")
        if per_material_color_textures and faces_by_mat:
            f.write(f"mtllib {obj_name}.mtl\n")
        elif have_tex:
            f.write(f"mtllib {obj_name}.mtl\n")
        f.write(f"o {obj_name}\n")
        for i in range(n_v):
            f.write(
                f"v {all_v[3 * i]:.6f} {all_v[3 * i + 1]:.6f} {all_v[3 * i + 2]:.6f}\n"
            )
        for i in range(n_vt):
            f.write(f"vt {all_vt[2 * i]:.6f} {all_vt[2 * i + 1]:.6f}\n")

        def emit_faces(fs: list[tuple[int, int, int, int, int, int]]) -> None:
            for v0, t0, v1, t1, v2, t2 in fs:
                if has_uv and t0 != 0:
                    f.write(f"f {v0}/{t0} {v1}/{t1} {v2}/{t2}\n")
                else:
                    f.write(f"f {v0} {v1} {v2}\n")

        if per_material_color_textures and faces_by_mat:
            for mat_name, fs in faces_by_mat.items():
                f.write(f"usemtl {mat_name}\n")
                emit_faces(fs)
        else:
            if have_tex:
                f.write(f"usemtl {obj_name}\n")
            emit_faces(flat_faces)

    print(
        f"  [conv] -> {obj_path.name}"
        + (" (+ multi-mat mtl + per-mat textures)" if per_material_color_textures and faces_by_mat
           else (" (+ mtl + texture)" if have_tex else ""))
    )


def extract_blend_diffuse(
    blend_path: Path,
    out_dir: Path,
    pick_index: int | None = None,
) -> Path | None:
    """Varre um ``.blend`` em busca de imagens PNG/JPEG empacotadas e
    retorna o mapa difuso / *base color* mais provável.

    O Blender guarda imagens empacotadas como bytes brutos dentro de
    blocos ``PackedFile``, então não precisamos do ``bpy`` para isso:
    basta varrer o binário pelas assinaturas de PNG/JPEG e os
    arquivos saem inteiros.

    Heurística de escolha do difuso:
        1. Descarta imagens pequenas (< 512×512), que costumam ser
           thumbnails ou ícones.
        2. Descarta imagens em escala de cinza (``mode='L'``) e
           quase-cinza (desvio padrão por canal muito próximo do
           delta médio): tipicamente são mapas de AO, roughness ou
           metalness.
        3. Descarta imagens onde o azul domina por uma margem
           confortável sobre os outros canais — são mapas de normal
           em tangent space.
        4. Do que sobrar, escolhe a imagem colorida com maior
           resolução.

    O parâmetro ``pick_index`` permite que o chamador ignore a
    heurística e pegue o arquivo extraído pelo índice (0-based);
    útil quando a heurística falha.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    buf = blend_path.read_bytes()

    PNG_SIG = b"\x89PNG\r\n\x1a\n"
    PNG_END = b"IEND"
    JPEG_SIG = b"\xff\xd8\xff"
    JPEG_END = b"\xff\xd9"

    extracted: list[Path] = []
    pos = 0
    while True:
        i = buf.find(PNG_SIG, pos)
        if i < 0:
            break
        end = buf.find(PNG_END, i + 8)
        if end < 0:
            break
        end_chunk = end + 4 + 4
        out_path = out_dir / f"packed_{len(extracted):02d}.png"
        out_path.write_bytes(buf[i:end_chunk])
        extracted.append(out_path)
        pos = end_chunk

    pos = 0
    while True:
        i = buf.find(JPEG_SIG, pos)
        if i < 0:
            break
        end = buf.find(JPEG_END, i + 3)
        if end < 0:
            break
        end_total = end + 2
        if end_total - i < 1024:
            pos = end_total
            continue
        out_path = out_dir / f"packed_{len(extracted):02d}.jpg"
        out_path.write_bytes(buf[i:end_total])
        extracted.append(out_path)
        pos = end_total

    print(f"  [blend] {blend_path.name}: extracted {len(extracted)} packed image(s)")
    if not extracted:
        return None

    if pick_index is not None and 0 <= pick_index < len(extracted):
        chosen = extracted[pick_index]
        print(f"  [blend] -> diffuse picked by index {pick_index}: {chosen.name}")
        return chosen

    best: tuple[int, Path] | None = None  # (resolução, path)
    for p in extracted:
        try:
            with Image.open(p) as im:
                im.load()
                w, h = im.size
                if min(w, h) < 512:
                    continue
                if im.mode == "L":
                    continue
                arr = np.asarray(im.convert("RGB"))
                mean = arr.mean(axis=(0, 1))
                std = arr.std(axis=(0, 1))
                # Descarta atlases AO/roughness quase em escala de cinza.
                colour_range = max(mean) - min(mean)
                if colour_range < 6.0 and max(std) < 30.0:
                    continue
                # Descarta normal maps em tangent space (azul dominante).
                if mean[2] > mean[0] + 30 and mean[2] > mean[1] + 30:
                    continue
                resolution = w * h
                if best is None or resolution > best[0]:
                    best = (resolution, p)
        except Exception:
            continue

    if best is None:
        print("  [blend] heuristic could not pick a diffuse; falling back to first")
        return extracted[0]
    print(f"  [blend] -> diffuse picked by heuristic: {best[1].name}")
    return best[1]


def make_solid_color_texture(
    out_path: Path,
    rgb: tuple[float, float, float],
    size: int = 256,
    noise_amp: float = 8.0,
) -> None:
    """Gera uma textura *tile-able* de cor sólida com um leve ruído.

    Os componentes em ``rgb`` são floats em 0..1 (formato do
    ``COLOR_DIFFUSE`` do Assimp). Adicionamos um pouco de ruído para
    que faces *flat-shaded* não fiquem com aparência completamente
    plástica e para que o JPEG comprima de forma significativa em
    vez de virar um único bloco constante.
    """
    seed = abs(hash(out_path.name)) & 0xFFFF
    rng = np.random.default_rng(seed)
    base = np.array([rgb[0] * 255.0, rgb[1] * 255.0, rgb[2] * 255.0], dtype=np.float32)
    noise = rng.normal(0.0, noise_amp, size=(size, size, 3)).astype(np.float32)
    arr = np.clip(base + noise, 0.0, 255.0).astype(np.uint8)
    Image.fromarray(arr).save(out_path, quality=92)


def make_brushed_metal_texture(out_path: Path, size: int = 1024) -> None:
    """Sintetiza uma textura *tile-able* de aço escovado para o piso
    interno (cinza médio + listras horizontais + leve tom azulado).
    Sem nenhum download externo: tudo é gerado proceduralmente a
    partir de uma RNG semeada, então o resultado é reprodutível."""
    rng = np.random.default_rng(7)
    base = np.full((size, size, 3), (170, 175, 185), dtype=np.float32)
    noise = rng.normal(0.0, 18.0, size=(size, size)).astype(np.float32)
    streaks = np.cumsum(rng.normal(0.0, 1.2, size=(size, size)).astype(np.float32), axis=1)
    streaks -= streaks.mean()
    streaks *= 1.6 / max(streaks.std(), 1e-6)
    streaks = np.clip(streaks * 9.0, -22.0, 22.0)
    base[..., 0] += noise + streaks
    base[..., 1] += noise + streaks * 0.95
    base[..., 2] += noise + streaks * 0.85
    plate_band = (np.arange(size) % (size // 8) < 2).astype(np.float32)[:, None] * -25.0
    base += plate_band[..., None]
    arr = np.clip(base, 25.0, 240.0).astype(np.uint8)
    Image.fromarray(arr).save(out_path, quality=92)
    print(f"  [tex] generated brushed metal texture -> {out_path.name}")


def main() -> int:
    print("[build_assets] starting")

    # ---------- (0) textura compartilhada de aço escovado para o interior ----------
    TEX_INTERIOR.parent.mkdir(parents=True, exist_ok=True)
    if not TEX_INTERIOR.exists():
        make_brushed_metal_texture(TEX_INTERIOR)

    # ---------- (1) submarino: .obj limpo + Base_Color.png real ----------
    submarine_obj_src = STAGING / "submarine_v2" / "submarine.obj"
    submarine_tex_src = STAGING / "submarine_v2" / "Base_Color.png"
    if submarine_obj_src.exists() and submarine_tex_src.exists():
        copy_obj_with_texture(
            submarine_obj_src,
            ASSETS / "submarino",
            "submarino",
            submarine_tex_src,
            "submarino_basecolor.png",
        )
    else:
        print(
            f"[warn] submarine assets missing under {STAGING / 'submarine_v2'}",
            file=sys.stderr,
        )

    # Joystick 2 (.fbx multi-material, sem nenhuma imagem de textura
    # embutida). A fonte fica em
    # objetos/joysticker_2/extracted/3d-model.fbx (já descompactado a
    # partir do download original do usuário). Passamos pelo
    # `assimp_to_obj` no modo `per_material_color_textures`: cada
    # material do Assimp com um COLOR_DIFFUSE vira um pequeno .jpg
    # de cor sólida, o .mtl recebe um bloco por material e o .obj
    # emite os `usemtl` casados; assim o joystick mantém suas 13
    # cores distintas por parte.
    joystick_2_fbx = (
        PROJ_ROOT.parent / "objetos" / "joysticker_2"
        / "extracted" / "3d-model.fbx"
    )
    if joystick_2_fbx.exists():
        assimp_to_obj(
            joystick_2_fbx,
            ASSETS / "joystick_2",
            "joystick_2",
            None,
            None,
            per_material_color_textures=True,
        )
    else:
        print(f"[warn] joystick_2 FBX missing at {joystick_2_fbx}", file=sys.stderr)

    # Cadeira sci-fi (.obj + .mtl). Este segundo modelo já vem com
    # um .mtl multi-material limpo, mas usando apenas Kd sólido (sem
    # `map_Kd`). Sintetizamos um pequeno .jpg de cor sólida por
    # material a partir do Kd do autor (e do Ke para a "tela"
    # emissiva), e em seguida escrevemos um .mtl que referencia
    # essas texturas. Assim o nosso pipeline unlit consegue
    # renderizar cada parte da cadeira com a cor pretendida.
    chair_obj_src = (
        PROJ_ROOT.parent
        / "objetos"
        / "cadeira"
        / "uploads_files_2664895_chair+-+model+sci-fi+2.obj"
    )
    chair_mtl_src = (
        PROJ_ROOT.parent
        / "objetos"
        / "cadeira"
        / "uploads_files_2664895_chair+-+model+sci-fi+2.mtl"
    )
    if chair_obj_src.exists() and chair_mtl_src.exists():
        copy_obj_with_kd_textures(
            chair_obj_src,
            chair_mtl_src,
            ASSETS / "cadeira",
            "cadeira",
        )
    else:
        print(f"[warn] chair assets missing at {chair_obj_src}", file=sys.stderr)

    # ---------- (2) modelos que já vêm em .obj ----------
    # Coral (AlienTubes) -> Red_Diffuse
    coral_obj = STAGING / "coral" / "AlienTubes_Obj" / "AlienTubes.obj"
    coral_tex = STAGING / "coral" / "AlienTubes_Red_Diffuse.png"
    if coral_obj.exists() and coral_tex.exists():
        copy_obj_with_texture(
            coral_obj,
            ASSETS / "coral",
            "coral",
            coral_tex,
            "coral_diffuse.png",
        )

    # Pedra -> stone_01_albedo.jpg
    stone_obj = STAGING / "pedra" / "Stone_01_BaseTri.OBJ"
    stone_tex = STAGING / "pedra" / "stone_01_albedo.jpg"
    if stone_obj.exists() and stone_tex.exists():
        copy_obj_with_texture(
            stone_obj,
            ASSETS / "pedra",
            "pedra",
            stone_tex,
            "pedra_albedo.jpg",
        )

    # Mesa sci-fi (.obj + .mtl + 9 materiais). O zip do .obj traz um
    # .mtl limpo que usa cores Kd para 7 dos 9 materiais e referencia
    # duas imagens de HUD (`futuristic-hud-15-.jpg` e `Hud 2.png`)
    # nos outros dois. Essas imagens NÃO estão dentro do zip do
    # .obj, mas estão empacotadas dentro do .fbx correspondente.
    # Então extraímos as duas uma vez, renomeamos para os nomes
    # exatos que o .mtl pede, e jogamos tudo em
    # `copy_obj_mixed_materials`.
    table_obj = STAGING / "table" / "obj" / "Sci Fi Table.obj"
    table_mtl = STAGING / "table" / "obj" / "Sci_Fi_Table.mtl"
    table_fbx = PROJ_ROOT.parent / "objetos" / "table" / "uploads_files_6054109_fbx.zip"
    if table_obj.exists() and table_mtl.exists() and table_fbx.exists():
        table_tex_dir = STAGING / "table" / "extracted_textures"
        table_tex_dir.mkdir(parents=True, exist_ok=True)
        # Primeiro extraímos o .fbx; depois varremos os bytes em
        # busca de PNG/JPEG empacotados. O `extract_blend_diffuse`
        # faz a varredura in-place, mas aqui precisamos das *duas*
        # imagens nomeadas exatamente como o .mtl pede, então
        # repetimos a lógica de scan de assinaturas (PNG_SIG /
        # JPEG_SIG) inline.
        fbx_root = STAGING / "table_fbx"
        fbx_root.mkdir(parents=True, exist_ok=True)
        import subprocess
        subprocess.run(
            ["bsdtar", "-xf", str(table_fbx), "-C", str(fbx_root)],
            check=True,
        )
        fbx_path = next(fbx_root.rglob("*.fbx"))
        buf = fbx_path.read_bytes()
        png_sig = b"\x89PNG\r\n\x1a\n"
        jpg_sig = b"\xff\xd8\xff"
        # PNG -> Hud 2.png  (HUD médica com a silhueta humana)
        i = buf.find(png_sig)
        if i >= 0:
            j = buf.find(b"IEND", i + 8)
            if j > 0:
                end = j + 8
                (table_tex_dir / "Hud 2.png").write_bytes(buf[i:end])
                print(f"  [tex] extracted FBX-packed PNG -> 'Hud 2.png'")
        # JPEG -> futuristic-hud-15-.jpg  (o HUD circular de mostradores)
        i = buf.find(jpg_sig)
        if i >= 0:
            j = buf.find(b"\xff\xd9", i + 3)
            if j > 0:
                end = j + 2
                (table_tex_dir / "futuristic-hud-15-.jpg").write_bytes(buf[i:end])
                print(f"  [tex] extracted FBX-packed JPEG -> 'futuristic-hud-15-.jpg'")
        copy_obj_mixed_materials(
            table_obj,
            table_mtl,
            ASSETS / "mesa",
            "mesa",
            texture_search_dirs=[table_tex_dir, table_mtl.parent],
        )
    else:
        print(f"[warn] sci-fi table assets missing", file=sys.stderr)

    # Estação de monitoramento -> dois materiais: 'table' e
    # 'hologram_glass'. A fonte já está extraída em
    # objetos/monitoring-station/, então não precisamos descompactar
    # nada em tempo de build.
    station_root = PROJ_ROOT.parent / "objetos" / "monitoring-station"
    station_obj = station_root / "source" / "Stol2.obj"
    station_tex_table = station_root / "textures" / "table_Base_color.png"
    station_tex_holo = station_root / "textures" / "hologram_glass_Base_color.png"
    if station_obj.exists() and station_tex_table.exists() and station_tex_holo.exists():
        copy_obj_multi_material(
            station_obj,
            ASSETS / "estacao",
            "estacao",
            {
                "table": (station_tex_table, "estacao_table.png"),
                "hologram_glass": (station_tex_holo, "estacao_hologram.png"),
            },
        )
    else:
        print(f"[warn] monitoring station assets missing under {station_root}", file=sys.stderr)

    # Alga: .obj + .mtl com um único material e map_Kd ->
    # seaweed_diffuse.png. A textura vem em um .zip irmão que já
    # extraímos em objetos/alga/textures_extracted/. Comporta-se
    # exatamente como coral/pedra: 1 modelo, 1 mapa difuso, sem
    # nenhuma mágica multi-material.
    alga_root = PROJ_ROOT.parent / "objetos" / "alga"
    alga_obj = alga_root / "uploads_files_2301153_seaweedList.obj"
    alga_tex = alga_root / "textures_extracted" / "seaweed_diffuse.png"
    if alga_obj.exists() and alga_tex.exists():
        copy_obj_with_texture(
            alga_obj,
            ASSETS / "alga",
            "alga",
            alga_tex,
            "alga_diffuse.png",
        )
    else:
        print(f"[warn] alga assets missing under {alga_root}", file=sys.stderr)

    # ---------- (3) animais marinhos (.obj + .mtl só com Kd) ----------
    # Cada um vem com um .obj Wavefront e um .mtl exportado pelo
    # Blender cujos materiais setam apenas Kd (sem map_Kd, sem
    # arquivo de textura). Passamos pelo `copy_obj_with_kd_textures`
    # para sintetizar um JPEG sólido pequeno por material, de modo
    # que o pipeline unlit consiga renderizá-los direto.

    palhaco_obj = (
        PROJ_ROOT.parent / "objetos" / "peixe_palhaco"
        / "obj_extracted" / "pez3.obj"
    )
    palhaco_mtl = palhaco_obj.with_suffix(".mtl")
    if palhaco_obj.exists() and palhaco_mtl.exists():
        # Material.005 na fonte do Blender é um plano de fundo
        # 30×30 (o "skybox" azul que o artista usou enquanto
        # modelava); descartamos para que sobre apenas a geometria
        # real do peixe.
        copy_obj_with_kd_textures(
            palhaco_obj,
            palhaco_mtl,
            ASSETS / "peixe_palhaco",
            "peixe_palhaco",
            skip_materials={"Material.005"},
        )
    else:
        print(f"[warn] peixe_palhaco assets missing at {palhaco_obj}", file=sys.stderr)

    orca_obj = (
        PROJ_ROOT.parent / "objetos" / "orca"
        / "uploads_files_6947089_Orca_LowPoly.obj"
    )
    orca_mtl = orca_obj.with_suffix(".mtl")
    if orca_obj.exists() and orca_mtl.exists():
        copy_obj_with_kd_textures(
            orca_obj,
            orca_mtl,
            ASSETS / "orca",
            "orca",
        )
    else:
        print(f"[warn] orca assets missing at {orca_obj}", file=sys.stderr)

    beluga_obj = (
        PROJ_ROOT.parent / "objetos" / "beluga"
        / "uploads_files_2833308_beluga.obj"
    )
    beluga_mtl = beluga_obj.with_suffix(".mtl")
    if beluga_obj.exists() and beluga_mtl.exists():
        copy_obj_with_kd_textures(
            beluga_obj,
            beluga_mtl,
            ASSETS / "beluga",
            "beluga",
        )
    else:
        print(f"[warn] beluga assets missing at {beluga_obj}", file=sys.stderr)

    print("[build_assets] done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
